balance tx with additional utxo map
Plutonomicon/cardano-transaction-lib pull request #1004
Opened 2022-09-07 16:19 UTC by the-headless-ghost

Closes #1000 .

@klntsky For now, I added the functions with the additional utxos. The function `evalTxExecutionUnits` will create the `additionalUtxoSet` argument for the `EvaluateTx` request.

### Pre-review checklist

- [ ] All code has been formatted using our config (`make format`)
- [ ] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2022-09-14 13:01 UTC, klntsky commented
@the-headless-ghost sorry for slow response. Could you please resolve the conflicts?

2022-09-14 17:41 UTC, klntsky requested changes

2022-09-14 17:41 UTC, klntsky commented on src/BalanceTx/ExUnitsAndMinFee.purs
> +-- <<<<<<< HEAD
Please remove this leftover

2022-09-15 07:01 UTC, the-headless-ghost commented on src/BalanceTx/ExUnitsAndMinFee.purs
> +-- <<<<<<< HEAD
oh right, totally forgot.

2022-09-15 07:27 UTC, the-headless-ghost commented
I just noticed that the `UtxoMap` type changed. Instead of `TransactionOutput` we have `TransactionOutputWithRefScript`. I don't know if this still makes sense in this context. Should I keep this type, or should I change it to `Map TransactionInput TransactionOutput`?

2022-09-15 21:53 UTC, klntsky commented
Reopening as #1046. We need it to be on a local branch for CI to run.

2022-09-15 21:53 UTC, closed without merging