Amir/1001 convert data cbor
Plutonomicon/cardano-transaction-lib pull request #1019
Opened 2022-09-11 21:03 UTC by amirmrad

Closes #1001 .

### Pre-review checklist

- [ ] All code has been formatted using our config (`make format`)
- [ ] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2022-09-12 11:09 UTC, ngua requested changes

2022-09-12 11:09 UTC, ngua commented on src/Serialization/PlutusData.purs
> +serialiseData :: forall a. ToData a => a -> Maybe CborBytes
Missing a kind signature here

2022-09-12 11:09 UTC, ngua commented on src/Deserialization/PlutusData.purs
> +deserialiseData :: forall a. FromData a => CborBytes -> Maybe a
Missing kind signature

2022-09-13 11:57 UTC, klntsky requested changes
Please use `Deserialization.FromBytes` machinery

2022-09-13 12:54 UTC, klntsky requested changes

2022-09-13 12:54 UTC, amirmrad commented on src/Serialization/PlutusData.js
> +exports._plutusDataToBytes = data => data.to_bytes();
will do

2022-09-13 13:59 UTC, klntsky requested changes

2022-09-13 13:59 UTC, klntsky commented on src/Serialization.purs
> +serialiseData :: forall (a :: Type). ToData a => a -> Maybe CborBytes
We need to re-export this function as part of `Contract` interface. I think `Contract.PlutusData` is a good place for it.

`deserializeData` should go there as well.

2022-09-13 13:59 UTC, klntsky commented on CHANGELOG.md
> +- Added conversion functions between `PlutusData` and `CborBytes` ([#1001](https://github.com/Plutonomicon/cardano-transaction-lib/issues/1001))
Please add names of the functions, with module names: `Contract.PlutusData.serializeData` and `Contract.PlutusData.deserializeData`

2022-09-14 12:28 UTC, klntsky approved these changes

2022-09-14 12:52 UTC, merged