Jy14898/module org
Plutonomicon/cardano-transaction-lib pull request #1039
Opened 2022-09-14 19:58 UTC by jy14898

Closes #820.

### Pre-review checklist

- [ ] All code has been formatted using our config (`make format`)
- [ ] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2022-09-22 06:59 UTC, ngua reviewed
We should merge this in as soon as possible, but I have one comment: our convention so far has been to only capitalize the first letter in initialisms/acronyms. You've chosen `CTL`, but `Ctl` would be more consistent with our naming scheme. I won't insist on changing this, but what are your thoughts on that?

2022-09-22 07:01 UTC, ngua reviewed
Also, I don't think that we should change `Contract` to `CTL.Contract`:
- It's reasonable to reserve the `Contract` namespace for CTL, especially since the likelihood of name clashes with user modules or modules from other libraries is very low
- it will make upgrading less pleasant for users

2022-09-22 10:19 UTC, jy14898 commented
> our convention so far has been to only capitalize the first letter in initialisms/acronyms. You've chosen `CTL`, but `Ctl` would be more consistent with our naming scheme. 

I thought about this a little, modules in the package set are somewhat split, I hadn't surveyed our own. I could make an argument to keep it how it is (but maybe not convincing): CIP/JSON/CBOR are all acronyms, they're pronounced the way they're spelled and are a new word. CTL is an initialism, where we pronounce the individual letters, and afaik no-one says seetle.

It's easy to change though 🤷

> Also, I don't think that we should change `Contract` to `CTL.Contract`

I placed them all under CTL for consistency, but I suppose ideally users don't see the CTL namespace anyway, so it's no more consistent.

What about `CTL.Plutus`? Drop the CTL there too?

2022-09-22 10:21 UTC, jy14898 commented
I suppose by my argument, JsonWsp should be JsonWSP and JsWebSocket JSWebSocket, FfiHelpers FFIHelpers... I'll change it to Ctl

2022-09-22 13:55 UTC, jy14898 commented
@ngua 

> I would move `Plutus` modules to `Ctl.Internal`. Ideally we expose everything through `Contract`

I'll have to make the re-exports then, we don't re-export `Plutus` yet we use it in the examples. Actually I'll leave re-exporting for a later PR

2022-09-23 09:15 UTC, ngua commented
@jy14898 I'd like to merge #1034 first, then we can merge this. Sorry to make you fix more merge conflicts :(

2022-09-23 09:26 UTC, jy14898 commented
> @jy14898 I'd like to merge #1034 first, then we can merge this. Sorry to make you fix more merge conflicts :(

No worries, better to be me than others

2022-09-23 10:44 UTC, ngua requested changes
Very excited for this change!

Please update the module name in the `spago test` invocation in `test/ctl-e2e-test.sh`

2022-09-23 11:00 UTC, ngua requested changes

2022-09-23 11:00 UTC, ngua commented on templates/ctl-scaffold/flake.nix
> +      rev = "39fc516c7c837401427b46637dacd9c7ada6274d";
You should also run `nix flake lock` to update the lockfile

2022-09-27 03:48 UTC, ngua approved these changes

2022-09-27 03:48 UTC, merged