Switch to multi-asset coin selection algorithm
Plutonomicon/cardano-transaction-lib pull request #1077
Opened 2022-10-01 16:17 UTC by errfrom

Closes # .

### Pre-review checklist

- [x] All code has been formatted using our config (`make format`)
- [ ] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2022-10-24 17:43 UTC, klntsky requested changes
We definitely need more tests. Maybe we can try running some of the test contracts with the new strategy.

2022-10-24 17:43 UTC, klntsky commented on src/Internal/BalanceTx/BalanceTx.purs
> +    foldr (+) zero <$> traverse (minCoinFor <<< fst) pairsAtStart
```suggestion
    sum <$> traverse (minCoinFor <<< fst) pairsAtStart
```

2022-10-25 10:07 UTC, jy14898 commented on src/Internal/BalanceTx/BalanceTx.purs
> +    performCoinSelection >>= \selectionState ->
Might as well just use do notation here
```suggestion
    selectionState <- performCoinSelection
```

2022-10-26 11:32 UTC, errfrom commented
@klntsky The new selection strategy is now used by default, so all our test contracts are executed using it.

2022-11-02 14:29 UTC, klntsky reviewed
Overall very good, I will return to it later for a more in-depth review

2022-11-02 14:29 UTC, klntsky commented on src/Internal/BalanceTx/CoinSelection.purs
> +data SelectionPriority = SelectionPriorityCover | SelectionPriorityImprove
Please describe how these alternatives affect the algorithm

2022-11-16 18:00 UTC, klntsky commented
Do not merge, the target is wrong.

2022-12-03 07:18 UTC, uhbif19 commented
@klntsky @errfrom Closing, cuz there is newer PR.

2022-12-03 07:18 UTC, closed without merging