added logLevel for customLogger
Plutonomicon/cardano-transaction-lib pull request #1098
Opened 2022-10-10 14:25 UTC by pb99u069

Closes # .

### Pre-review checklist

- [ ] All code has been formatted using our config (`make format`)
- [ ] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2022-10-10 14:32 UTC, pb99u069 commented
this change doesn't need to be noted in the Changelog, I guess?

2022-10-10 14:42 UTC, klntsky requested changes

2022-10-10 14:42 UTC, klntsky commented on src/Contract/Config.purs
> +  , customLogLevel: Trace
We already have log level here, please remove.

2022-10-10 14:42 UTC, klntsky commented on src/Contract/Monad.purs
>    , customLogger :: Maybe (Message -> Aff Unit)
```suggestion
  , customLogger :: Maybe (LogLevel -> Message -> Aff Unit)
```

It should accept a log level for filtering

2022-10-10 14:43 UTC, klntsky commented
> this change doesn't need to be noted in the Changelog, I guess?

It changes a type of a public function, so it must be mentioned

2022-10-11 12:05 UTC, pb99u069 commented
@klntsky I'm struggling with this issue. does what I've done to here make sense in any way? I don't see where the filtering for the customLogger should be implemented

2022-10-11 12:47 UTC, closed without merging