Add CI check on the use of internal CTL modules in examples
Plutonomicon/cardano-transaction-lib pull request #1142
Opened 2022-10-24 15:48 UTC by errfrom

Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/1042

### Pre-review checklist

- [x] All code has been formatted using our config (`make format`)
- [x] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [x] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2022-10-24 17:50 UTC, klntsky requested changes

2022-10-24 17:50 UTC, klntsky commented on examples/SignMultiple.purs
> +  , TxOutRefCache
We definitely should not expose `TxOutRefCache`. Let's remove logging of locked outputs (it's not good to expose the internals to the user anyway, and we don't have any assertions here).

2022-10-25 11:15 UTC, jy14898 requested changes

2022-10-25 11:15 UTC, jy14898 commented on .github/workflows/examples-imports-check.yml
> +      - run: bash .github/workflows/scripts/examples-imports-check.sh
I'd prefer this to be available in the makefile and run in hydra like `formatting-check` in `flake.nix`, rather than a github action

2022-10-26 13:42 UTC, jy14898 approved these changes
LGTM

2022-10-26 13:47 UTC, klntsky requested changes

2022-10-26 13:47 UTC, klntsky commented on Makefile
> +check-examples-imports:
Please add it to check-format as a dependency

2022-10-27 15:36 UTC, klntsky approved these changes

2022-10-31 17:27 UTC, merged