Use Kupo instead of Ogmios for `utxosAt` query
Plutonomicon/cardano-transaction-lib pull request #1185
Opened 2022-11-05 17:56 UTC by errfrom

Closes # .

### Pre-review checklist

- [ ] All code has been formatted using our config (`make format`)
- [ ] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2022-11-13 13:36 UTC, jy14898 commented on nix/runtime.nix
> +      # TODO: Do we want to support connection through ogmios?
Would connecting via ogmios solve issues with synchronization issues between submission + utxos at?

2022-11-13 13:37 UTC, jy14898 commented on nix/runtime.nix
> +      kupoDbVol = "kupo-db";
Should we make this per-network?

2022-11-14 17:57 UTC, klntsky reviewed
Looks good, except of what Joseph has already pointed out

2022-11-15 16:47 UTC, errfrom commented on nix/runtime.nix
> +      # TODO: Do we want to support connection through ogmios?
Created an issue: https://github.com/Plutonomicon/cardano-transaction-lib/issues/1226

2022-11-15 16:48 UTC, errfrom commented on webpack.config.js
> +    },
Created an issue: https://github.com/Plutonomicon/cardano-transaction-lib/issues/1227

2022-11-15 18:02 UTC, klntsky requested changes

2022-11-15 18:04 UTC, klntsky commented on templates/ctl-scaffold/packages.dhall
> +        , version = "b8c20088aa942281200b6d9e48baa833f3efc950"
Looks like you forgot to update `spago-packages.nix` here. Use `script/template-check.sh` to see if the template is usable.

2022-11-15 18:05 UTC, klntsky commented on CHANGELOG.md
> +- `utxosAt` and `getUtxo` now use Kupo internally, `utxosAt` returns `UtxoMap` without `Maybe` context ([#1185](https://github.com/Plutonomicon/cardano-transaction-lib/pull/1185))
Add a note that the config should be updated.

2022-11-15 18:07 UTC, klntsky commented on webpack.config.js
> +      "/matches": process.env.KUPO_HOST, // e.g. http://localhost:1442
We should add a default value. And update the comment that says it's necessary.

2022-11-16 13:00 UTC, closed without merging