WIP: Add NuFi wallet support
Plutonomicon/cardano-transaction-lib pull request #1265
Opened 2022-11-24 17:15 UTC by errfrom

Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/1263

### Pre-review checklist

- [x] All code has been formatted using our config (`make format`)
- [ ] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2022-11-25 14:37 UTC, errfrom commented
Currently blocked by [#1266: Handle NuFi signData response](https://github.com/Plutonomicon/cardano-transaction-lib/issues/1266)

2022-12-05 19:28 UTC, klntsky requested changes
Let's use `NuFi` instead of `Nufi` spelling everywhere

2022-12-09 14:33 UTC, klntsky approved these changes

2022-12-09 23:23 UTC, uhbif19 approved these changes

2022-12-12 11:10 UTC, merged