Fix concurrency problem in staking tests affecting CI
Plutonomicon/cardano-transaction-lib pull request #1360
Opened 2022-12-22 18:47 UTC by klntsky

2022-12-22 19:03 UTC, jy14898 requested changes
Other than these changes, LGTM

2022-12-22 19:18 UTC, jy14898 approved these changes
LGTM, small comment but not important

2022-12-22 19:18 UTC, jy14898 commented on test/Plutip/Staking.purs
> +  retiringPoolId <- liftEffect $ liftM (error "unable to decode poolId bech32")
I don't think this `liftEffect` is necessary, due to `liftM` being over any `m` with `MonadError Error m`

2022-12-22 23:58 UTC, rynoV approved these changes

2022-12-23 00:03 UTC, rynoV reviewed
Suggestion for changelog:

```
- Module `Contract.Transaction` now exports `mkPoolPubKeyHash` and `poolPubKeyHashToBech32` for bech32 string <-> `PoolPubKeyHash` conversion
```

2022-12-23 10:56 UTC, zmrocze commented
The spawn and configuration of this pool is handled at plutip level already: 
https://github.com/mlabs-haskell/plutip/blob/7f2d59abd911dd11310404863cdedb2886902ebf/src/Test/Plutip/Internal/Cluster.hs#L690
so the change could have been made there

2022-12-29 21:00 UTC, merged