blockfrost Get current epoch information
Plutonomicon/cardano-transaction-lib pull request #1372
Opened 2022-12-30 06:33 UTC by Luis-omega

Part of #1365 

### Pre-review checklist

- [ ] All code has been formatted using our config (`make format`)
- [ ] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2023-01-03 16:47 UTC, jy14898 commented
I'd like to take over this PR, given Luis is finishing work on CTL

2023-01-16 15:01 UTC, errfrom requested changes
LGTM, but please update `spago-packages.nix` of the template and extract `ProtocolParameters` into a separate module

2023-01-16 15:09 UTC, jy14898 commented on templates/ctl-scaffold/packages.dhall
> +        , version = "90b8fc187d61e6e3b91290339dc8039190cbfece"
I think the generated file already contains all the needed dependencies, we moved a transitive dep to a direct one. I'll check though

2023-01-17 11:03 UTC, jy14898 commented on templates/ctl-scaffold/packages.dhall
> +        , version = "90b8fc187d61e6e3b91290339dc8039190cbfece"
Oh, I see

2023-01-17 14:23 UTC, errfrom approved these changes

2023-01-17 14:35 UTC, merged