Seungheonoh/npm submodule
Plutonomicon/cardano-transaction-lib pull request #1460
Opened 2023-03-20 19:12 UTC by SeungheonOh

Closes #1457.

### Pre-review checklist

- [x] All code has been formatted using our config (`make format`)
- [ ] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2023-03-23 15:54 UTC, klntsky commented on nix/default.nix
> +            "cp ${modulePath} ./${builtins.baseNameOf (builtins.toString modulePath)} -r")
Thanks @aciceri ! Yep, to me it looks like linkFarm is strictly better

2023-03-23 15:55 UTC, klntsky requested changes
See comment

2023-03-23 15:57 UTC, SeungheonOh commented on nix/default.nix
> +            "cp ${modulePath} ./${builtins.baseNameOf (builtins.toString modulePath)} -r")
Thank you. I'll make the change to use linkFarm. I didn't know it existed

2023-03-23 19:55 UTC, SeungheonOh commented
Fixed

2023-03-28 11:40 UTC, klntsky commented on nix/default.nix
> +  # Path to submodule locations that needs to be copied when making node env
```suggestion
  # Paths to submodule locations that need to be copied when making node env
```

2023-03-28 11:43 UTC, klntsky requested changes
I am not sure this is the right usage of linkFarm. `cp -r` is still used.

2023-03-28 11:49 UTC, SeungheonOh commented
package.json and package-lock.json are expected to be a file to be used in node2nix. Not much can be done here

2023-03-28 18:35 UTC, klntsky commented on nix/default.nix
> +            "cp ${modulePath} ./${builtins.baseNameOf (builtins.toString modulePath)} -r")
@aciceri could you please take a look again?

2023-03-28 20:51 UTC, SeungheonOh commented
@aciceri bump

2023-03-29 13:10 UTC, aciceri approved these changes
@SeungheonOh Only two perplexities:
- what happens if `submodules` is `[]`? I guess you do a `cp <linkFarmOut>/* . -r` where `<linkFarmOut>` is an empty folder. If you want you could directly avoid the entire line if there are no submodules
- what happens if one wants to use a submodule which is the output of another derivation? For instance consider
```nix
submodules = [
  (pkgs.runCommand "foo-submodule" {} "mkdir -p $out/foo; magic > $out/foo")
];
```
The `builtins.baseNameOf` this derivation would be `foo-submodule` (I believe, haven't tested it). Is this what you want? I would make a test to check if this works.
Moreover I really don't like depending on `builtins.baseNameOf`, it looks flaky. But I can't give you any alternative that doesn't imply making the UI more complex:
```nix
submodule = [
 {
   name = "foo";
   path = ./foo-submodule;   
 }
 {
   name = "bar";
   path = mkBarSubmodule { inherit pkgs; src = ./bar-stuff; };   
 }
];
```

Said this, if it works it looks good to me, these are improvements that can be made when (and if) these problems arise.

2023-03-29 20:03 UTC, SeungheonOh commented
Thanks for the review. I haven't consider using output of derivation as a submodule. Mainly, it was intended for subdirectories.

Because I was mainly considering subdirectories, `builtins.baseNameOf` was good as it gave concise and consistent paths to be imported in `package.json`. That being said, I'm also happy with explicit path.

2023-04-06 11:38 UTC, emiflake commented on nix/default.nix
> +      }/* . -r
Here's a patch for what @klntsky suggested.

```suggestion
      ${pkgs.lib.optionalString (builtins.length submodules != 0) "cp ${
        pkgs.linkFarm "node-packages-${projectName}-source"
          (builtins.map (path: {
            inherit path;
            name = builtins.baseNameOf (builtins.toString path);
          }) submodules)
      }/* . -r"}
```

2023-06-01 14:32 UTC, aciceri commented
@klntsky In my opinion it's already mergeable.

2023-07-03 11:23 UTC, emiflake commented
Once again bumping this PR :)
@klntsky
If it needs a rebase, or whatnot I'd be happy to help.

2025-01-27 14:35 UTC, merged