Add EncodeAeson stuff.
Plutonomicon/cardano-transaction-lib pull request #404
Opened 2022-05-11 18:22 UTC by adamczykm

This adds support for EncodeJson equivalent for Aesons. It will most likely be useful for CTL-bridge things.
- [ ] tests todo

2022-05-12 06:43 UTC, ngua requested changes
Please remove the `Contract` imports

We should export the new typeclass from `Contract.Aeson`. We might want to add instances for various Plutus types as well

Are you planning on implementing the tests in this PR as well?

2022-05-12 06:43 UTC, ngua commented on src/Aeson.purs
> +import Contract.Prelude (Tuple(..), length, sequence)
`Contract` imports

2022-05-12 06:43 UTC, ngua commented on src/Aeson.purs
> +genNextNumberIndex = AesonEncoder (get <* modify_ (\s -> s + 1))
Personal style opinion: I'd prefer a section here

2022-05-12 06:43 UTC, ngua commented on src/Aeson.purs
> +bumpNumberIndexBy i = AesonEncoder (modify_ (\s -> s + i))
Here as well

2022-05-12 08:03 UTC, adamczykm commented
Yes, I'll add some today.

2022-05-13 04:08 UTC, ngua approved these changes
Looks good. Could you just add a `Contract` export for the new class?

2022-05-13 14:51 UTC, klntsky approved these changes

2022-05-13 22:27 UTC, adamczykm commented on src/Aeson.purs
> +genNextNumberIndex = AesonEncoder (get <* modify_ ((+) 1))
Ok

2022-05-16 05:55 UTC, merged