TokenName fixes
Plutonomicon/cardano-transaction-lib pull request #537
Opened 2022-06-13 11:00 UTC by bladyjoker

Closes # .

### Pre-review checklist

- [ ] All code has been formatted using our config (`make format` for Purescript, `nixpkgs-fmt` for Nix)
- [ ] All Purescript imports are explicit, including constructors
- [ ] **All** existing examples have been run locally against a fully-synced testnet node
- [ ] The integration and unit tests have been run (`npm run test`) locally
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`)

2022-06-15 04:02 UTC, ngua requested changes

2022-06-15 04:04 UTC, ngua commented
@bladyjoker You can run the examples by launching the runtime as normal and then use `npm run dev` to run `AlwaysSucceeds`. Then you can edit the `ps-entrypoint` variable in the Makefile to run other examples

For the changelog, I do think this is worth mentioning under `### Fixed`

2022-06-15 06:59 UTC, bladyjoker commented on src/Serialization.purs
> +foreign import newAssetName :: ByteArray -> Effect AssetName
How do you feel generally about keeping CborBytes, but instead of RawBytes just to use ByteArray as it already denotes the same thing?

2022-06-15 07:00 UTC, bladyjoker commented on Makefile
> +.PHONY: autogen-deps run-testnet-node run-testnet-ogmios clean
For consistency I added all the existing makefile targets in the phony.

2022-06-15 07:13 UTC, bladyjoker commented on Makefile
> +clean:
I guess not, but some files are write protected and honestly -f just makes me not think twice about this.

```
rm: remove write-protected regular file '.spago/nullable/v5.0.0/.git/objects/pack/pack-787492eedb3c946f432fe669ac1580658271ca80.pack'? y
```

2022-06-15 07:21 UTC, bladyjoker commented on src/Types/TokenName.js
> +// FIXME: Move this to a better location
That's a great policy to have https://github.com/Plutonomicon/cardano-transaction-lib/issues/548

2022-06-15 07:23 UTC, bladyjoker commented on src/Types/TokenName.js
> +var TextDecoder =
I thought `var` is preferred to declared scoped variables? It's been a while since I dealt with Js so I don't know how things are done nowadays...

2022-06-15 07:31 UTC, bladyjoker commented on src/Types/TokenName.js
> +    (typeof window === 'object' && window.TextDecoder) ||
I wonder if it makes sense to consolidate all this in a single place and then `dependency inject` the whole environment via a dictionary that has all libraries used resolved properly and bound. But afaict that would require us to thread this dictionary everywhere which is a no go.

It's not important, just dumping some thoughts here :)

2022-06-15 07:45 UTC, ngua commented on src/Types/TokenName.js
> +var TextDecoder =
`let` or `const` should be preferred, `const` can't be reassigned while `let` can

2022-06-15 07:46 UTC, ngua commented on Makefile
> +clean:
Oh right I forgot there might be git repos in there

2022-06-15 07:46 UTC, ngua commented on Makefile
> +.PHONY: autogen-deps run-testnet-node run-testnet-ogmios clean
None of those targets exist anymore though

2022-06-15 07:47 UTC, ngua commented on src/Serialization.purs
> +foreign import newAssetName :: ByteArray -> Effect AssetName
Well, that would be a pretty big change that's outside of the scope of this PR. I think it's better to have `ByteArray` as a more agnostic type

2022-06-15 07:52 UTC, ngua commented on src/Types/TokenName.js
> +    (typeof window === 'object' && window.TextDecoder) ||
That's a good idea. We have a ton of replicated checks across the FFI modules. We can open an issue for this as well

2022-06-15 08:12 UTC, bladyjoker commented on src/Types/TokenName.purs
> +          let stripped = drop 3 tkstr
Tried my best, this whole thing is a crime against humanity and with recent plutus-ledger-api update it's gone anyway, so let's get rid of this when we upgrade

2022-06-15 08:13 UTC, bladyjoker commented on src/Types/TokenName.js
Added a link to https://github.com/Plutonomicon/cardano-transaction-lib/issues/544. TLDR; The utf8 decoding libraries for purescript don't fail on invalid utf8 byte sequences, which could be pretty scary if I could come up with a way to exploit this behavior x)

2022-06-15 08:15 UTC, bladyjoker commented on Makefile
> +.PHONY: autogen-deps run-testnet-node run-testnet-ogmios clean
I mean, I updated the phony so it reflects the existing targets

2022-06-15 08:16 UTC, bladyjoker commented on src/Types/TokenName.js
> +var TextDecoder =
Used `let`

2022-06-15 08:25 UTC, bladyjoker commented on src/Types/TokenName.js
> +    (typeof window === 'object' && window.TextDecoder) ||
https://github.com/Plutonomicon/cardano-transaction-lib/issues/549

2022-06-15 08:31 UTC, bladyjoker commented
>

2022-06-15 08:32 UTC, bladyjoker commented
> @bladyjoker You can run the examples by launching the runtime as normal and then use `npm run dev` to run `AlwaysSucceeds`. Then you can edit the `ps-entrypoint` variable in the Makefile to run other examples

Hmm, my infra I use to test is at least 15+ days old, so some endpoints are not there any longer :sob: . I'll have to update the whole thing which is a pretty hefty endeavor.

2022-06-15 08:35 UTC, bladyjoker commented on src/Serialization.purs
> +foreign import newAssetName :: ByteArray -> Effect AssetName
Just to clarify, you'd like to keep the RawBytes and would like me to switch to using that in the context of this PR?

2022-06-15 09:06 UTC, ngua commented on src/Serialization.purs
> +foreign import newAssetName :: ByteArray -> Effect AssetName
Yes, that's what I was thinking

2022-06-15 11:06 UTC, klntsky approved these changes

2022-06-15 12:17 UTC, bladyjoker commented on src/Serialization.purs
> +foreign import newAssetName :: ByteArray -> Effect AssetName
Done!

2022-06-15 19:09 UTC, bladyjoker commented
@ngua I don't understand why I can't get the following to pass...

```
[DEBUG] 2022-06-15T19:03:29.296Z sending: {"args":{"query":{"utxo":["addr_test1qr7g8nrv76fc7k4ueqwecljxx9jfwvsgawhl55hck3n8uwaz26mpcwu58zdkhpdnc6nuq3fa8vylc8ak9qvns7r2dsysp7ll4d"]}},"me
thodname":"Query","mirror":"Query-i6dlq18rvl4fyob9n","servicename":"ogmios","type":"jsonwsp/request","version":"1.0"}                                                                    
Aff Int                                                                                                                                                                                  
  ✗ UtxosAt Testnet:                                                                                                                                                                     
                                                                                                                                                                                         
  test timed out after 2000ms                                                                                                                                                            
...
[DEBUG] 2022-06-15T19:03:31.294Z sending: {"args":{"query":{"utxo":["addr1qyc0kwu98x23ufhsxjgs5k3h7gktn8v5682qna5amwh2juguztcrc8hjay66es67ctn0jmr9plfmlw37je2s2px4xdssgvxerq"]}},"methodn
ame":"Query","mirror":"Query-i6dlq18rvl4fyoct7","servicename":"ogmios","type":"jsonwsp/request","version":"1.0"}                                                                         
[DEBUG] 2022-06-15T19:03:31.691Z message: {"type":"jsonwsp/response","version":"1.0","servicename":"ogmios","methodname":"Query","result":[[{"txId":"c5c905b500851a7da6ef2ae97bc6627ab8d7
60fd7300a1a63560cdc69f098112","index":0},{"address":"addr_test1qr7g8nrv76fc7k4ueqwecljxx9jfwvsgawhl55hck3n8uwaz26mpcwu58zdkhpdnc6nuq3fa8vylc8ak9qvns7r2dsysp7ll4d","value":{"coins":50000
00,"assets":{}},"datum":null}],[{"txId":"c5c905b500851a7da6ef2ae97bc6627ab8d760fd7300a1a63560cdc69f098112","index":1},{"address":"addr_test1qr7g8nrv76fc7k4ueqwecljxx9jfwvsgawhl55hck3n8u
waz26mpcwu58zdkhpdnc6nuq3fa8vylc8ak9qvns7r2dsysp7ll4d","value":{"coins":994831683,"assets":{}},"datum":null}]],"reflection":"Query-i6dlq18rvl4fyob9n"}                                   
[ERROR] 2022-06-15T19:03:31.721Z unexpected parse error on input: {"type":"jsonwsp/response","version":"1.0","servicename":"ogmios","methodname":"Query","result":[[{"txId":"c5c905b50085
1a7da6ef2ae97bc6627ab8d760fd7300a1a63560cdc69f098112","index":0},{"address":"addr_test1qr7g8nrv76fc7k4ueqwecljxx9jfwvsgawhl55hck3n8uwaz26mpcwu58zdkhpdnc6nuq3fa8vylc8ak9qvns7r2dsysp7ll4d
","value":{"coins":5000000,"assets":{}},"datum":null}],[{"txId":"c5c905b500851a7da6ef2ae97bc6627ab8d760fd7300a1a63560cdc69f098112","index":1},{"address":"addr_test1qr7g8nrv76fc7k4ueqwec
ljxx9jfwvsgawhl55hck3n8uwaz26mpcwu58zdkhpdnc6nuq3fa8vylc8ak9qvns7r2dsysp7ll4d","value":{"coins":994831683,"assets":{}},"datum":null}]],"reflection":"Query-i6dlq18rvl4fyob9n"}           
  ✗ UtxosAt non-Testnet:                                                                                                                                                                 
                                                                                                                                                                                         
  test timed out after 2000ms                                                                                                                                                            
...
[DEBUG] 2022-06-15T19:03:34.204Z message: {"type":"jsonwsp/response","version":"1.0","servicename":"ogmios","methodname":"Query","result":[],"reflection":"Query-i6dlq18rvl4fyoct7"}
[ERROR] 2022-06-15T19:03:34.205Z unexpected parse error on input: {"type":"jsonwsp/response","version":"1.0","servicename":"ogmios","methodname":"Query","result":[],"reflection":"Query-i6dlq18rvl4fyoct7"}
...
Summary
12/14 tests passed

[error] Running failed; exit code: 1
```
I upgraded the CTL in the infrastructure (which uses CTL's inputs for Ogmios  and ODC)

2022-06-16 06:05 UTC, ngua approved these changes

2022-06-16 06:06 UTC, ngua commented
@bladyjoker I'd be fine with increasing the timeout (in another PR)

2022-06-16 06:06 UTC, merged