Add Map instances
Plutonomicon/cardano-transaction-lib pull request #633
Opened 2022-06-29 14:57 UTC by MitchyCola

This adds instances for `Map` in `FromMetadata`, `ToData`, and `FromData`. This also fixes the `Map` instance for `ToMetadata`, where the name of the exported variable was causing errors in a bundled `output.js`.

### Pre-review checklist

- [x] All code has been formatted using our config (`make format` for Purescript, `nixpkgs-fmt` for Nix)
- [x] All Purescript imports are explicit, including constructors
- [ ] **All** existing examples have been run locally against a fully-synced testnet node
- [ ] The integration and unit tests have been run (`npm run test`) locally
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`)

2022-06-29 19:13 UTC, klntsky commented
Plutus data uses a map that is backed by a kv-list. I am not sure at all these instances are correct (because of different handling of  duplicates). Could you please look into Plutus code, how is it handled there?

> the name of the exported variable

Which name?

2022-06-30 06:42 UTC, vvtran commented
I agree with @klntsky, we shouldn't be using `Data.Map.Map`, instead we should probably use `Plutus.Types.AssocMap.Map`

2022-06-30 06:44 UTC, vvtran commented
Unless there is a specific reason to use PureScript's Map?

2022-06-30 11:58 UTC, MitchyCola commented
> > the name of the exported variable
> 
> Which name?

@klntsky Previously, when I was trying to bundle while using `toMetadata` on a Map, I was getting this error:

```shell
ERROR in ./output.js 11088:10
Module parse failed: Unterminated string constant (11088:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   exports["toMetadataMap"] = toMetadataMap;
|   exports["toMetadataArray/\AnyToMet"] = toMetadataArray$div$bslashAnyToMet;
>   exports["toMetadataArray/\"] = toMetadataArray$div$bslash;
|   exports["toMetadataByteArray"] = toMetadataByteArray;
|   exports["toMetadataString"] = toMetadataString;
 @ ./main.js 8:0-21

webpack 5.67.0 compiled with 1 error in 610 ms
```

The backshlasses from the tuple symbol, `/\`, were being used to escape the quotation marks. So I swapped them out for `Tuple` in the instance declaration for `ToMetadata (Array (k /\ AnyToMetadata))` and `ToMetadata (Array (k /\ v))`, in `Metadata.ToMetadata`.

2022-06-30 11:59 UTC, MitchyCola commented
I was using `Data.Map` because `Metadata.ToMetadata` was already using it in its instances. I can look into using `Plutus.Types.AssocMap`.

2022-06-30 12:43 UTC, MitchyCola commented
I removed `Data.Map.Map` instances for `FromData` and `ToData`, there are instances for them in `Plutus.Types.AssocMap.Map`.

`Data.Map.Map` should be kept for `Metadata.FromMetadata` and `Metadata.ToMetadata`.

2022-07-05 00:42 UTC, MitchyCola commented
@vvtran  The simple answer would be that the type class definition for `Types.TransactionMetadata.TransactionMetadatum` uses `Data.Map.Map`. Which is also used in `Deserilization.Transaction`, 'Metadata.Helpers`, & `Serialization.AuxilaryData`

I suppose that it could be changed to `Plutus.Types.AssocMap.Map` to keep consistency. If it were to be changed, it would probably be better to do it in another PR.

2022-07-29 19:38 UTC, klntsky requested changes

2022-07-29 19:38 UTC, klntsky commented on CHANGELOG.md
> +- Rplaced `/\` with `Tuple` for the `Array Tuple` instances in `Metadata.ToMetadata` ([#633](https://github.com/Plutonomicon/cardano-transaction-lib/pull/633))
```suggestion
- Replaced `/\` with `Tuple` for the `Array Tuple` instances in `Metadata.ToMetadata` ([#633](https://github.com/Plutonomicon/cardano-transaction-lib/pull/633))
```

2022-07-29 19:38 UTC, klntsky commented on CHANGELOG.md
> +- `Data.Map.Map` instance for `Metadata.FromMetadata` ([#633](https://github.com/Plutonomicon/cardano-transaction-lib/pull/633))
```suggestion
- `Metadata.FromMetadata` instance for `Data.Map.Map` ([#633](https://github.com/Plutonomicon/cardano-transaction-lib/pull/633))
```

2022-08-18 07:15 UTC, ngua commented
There hasn't been much activity on this recently so I'm going to close it for now. If the instance is still required please feel free to reopen!

2022-08-18 07:15 UTC, closed without merging