Switch to Ogmios for execution units evaluation
Plutonomicon/cardano-transaction-lib pull request #665
Opened 2022-07-01 17:29 UTC by errfrom

Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/174

### Pre-review checklist

- [x] All code has been formatted using our config (`make format` for Purescript, `nixpkgs-fmt` for Nix)
- [x] All Purescript imports are explicit, including constructors
- [x] **All** existing examples have been run locally against a fully-synced testnet node
- [x] The integration and unit tests have been run (`npm run test`) locally
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`)

2022-07-01 21:14 UTC, klntsky requested changes
Great, thank you!

2022-07-01 21:14 UTC, klntsky commented on CHANGELOG.md
> +- POST /eval-ex-units Haskell server endpoint.
```suggestion
- `POST /eval-ex-units` Haskell server endpoint. 
```

2022-07-01 21:14 UTC, klntsky commented on test/Ogmios/EvaluateTx.purs
> +nat :: Int -> Natural
Please rename it to `fromInt` and move to `Types.Natural`

2022-07-02 05:14 UTC, ngua reviewed
I haven't had the change to look at this very closely yet, and I can't leave a comment on the relevant part of `server/src/Types.hs`, but we can remove everything related to the node socket now, right? AFAIK we only needed that to perform queries related to the ex units calculation

2022-07-04 07:57 UTC, vvtran commented on src/Types/RedeemerTag.purs
> +  | otherwise = Nothing
```
fromString :: String -> Maybe RedeemerTag
fromString = case _ of
  "spend" -> Just Spend
  "mint" -> Just Mint
  "certificate" -> Just Cert
  "withdrawal" -> Just Reward
  _ -> Nothing
```
might be nicer but down to you.

2022-07-04 07:57 UTC, vvtran commented on test/Ogmios/EvaluateTx.purs
> +nat = Natural.fromBigInt' <<< BigInt.fromInt
I would also add to perhaps re-export this from `Contract.Numeric.Natural`

2022-07-04 07:57 UTC, vvtran commented on src/QueryM/Ogmios.purs
> +    redeemerPtrTypeMismatch = TypeMismatch $
redundant `$`

2022-07-04 14:33 UTC, vvtran reviewed
Heads up @errfrom, I'm getting
```
Summary
2/16 tests passed
```
due to `(AtKey "coinsPerUtxoWord" MissingValue)`

Edit: ignore this

2022-07-04 14:37 UTC, vvtran commented
I think there was a PR somewhere that updated the field name `coinsPerUtxoWord` no? @jy14898

2022-07-04 14:38 UTC, errfrom commented
@vvtran Don't we have the changes related to the Babbage protocol parameters in `vasil` branch?

2022-07-04 14:40 UTC, errfrom commented
@vvtran I believe we'll need to make some minor changes in `BalanceTx` as well because of the new `coinsPerUtxoByte`

2022-07-04 14:42 UTC, vvtran commented
However, is this not a change we need to implement soon as our tests will continue to fail? A partial update happened yesterday right?

2022-07-04 14:43 UTC, vvtran commented
I think I didn't switch nodes properly perhaps.

2022-07-04 14:44 UTC, vvtran commented
Anyhow, I think 14/16 of the tests are passing on this branch anyway? So the posix time change is still required.

2022-07-04 14:53 UTC, vvtran commented
@errfrom  Apologies, please ignore my comments, I got pretty confused because I've been switching between branches with different nodes and the tests were confusing me, The tests are indeed _passing_.
cc: @klntsky @ngua

2022-07-04 17:03 UTC, klntsky approved these changes
I approve this but it's broken without Ogmios fork update

2022-07-05 10:55 UTC, ngua commented
I think we can close this since we need to merge `vasil` into `develop`, and these changes are already there

2022-07-05 10:55 UTC, closed without merging