Klntsky/683 deprecate d extraentropy
Plutonomicon/cardano-transaction-lib pull request #694
Opened 2022-07-06 22:46 UTC by klntsky

Closes #683 

[These](https://github.com/Emurgo/cardano-serialization-lib/pull/460/files) are just deprecations, but I think it's meaningful for us to remove them right now, because we don't really aim at supporting eras except the current one (since we don't handle older eras in Ogmios responses anyway). 

I updated the changelog in this PR in order not to forget (this is technically a breaking change, but it's extremely unlikely we have users of this feature right now).

### Pre-review checklist

- [x] All code has been formatted using our config (`make format` for Purescript, `nixpkgs-fmt` for Nix)
- [x] All Purescript imports are explicit, including constructors
- [ ] **All** existing examples have been run locally against a fully-synced testnet node
- [x] The integration and unit tests have been run (`npm run test`) locally
- [x] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`)

2022-07-07 07:19 UTC, jy14898 requested changes
Looks good to me once the typo is fixed, this doesn't break the ogmios fixture tests (not yet merged into babbage), as extra fields in the json are not an issue

2022-07-07 07:19 UTC, jy14898 commented on CHANGELOG.md
> +- `d` and `extraEntropy` protocol parameters from protocol paramters update proporsal
Typo of proposal

2022-07-07 07:20 UTC, jy14898 commented on CHANGELOG.md
> +- `d` and `extraEntropy` protocol parameters from protocol paramters update proporsal
and parameters

2022-07-08 06:01 UTC, ngua approved these changes

2022-07-08 06:01 UTC, merged