Query utxo by output reference
Plutonomicon/cardano-transaction-lib pull request #702
Opened 2022-07-07 16:27 UTC by rynoV

Adds `getUtxo` function implementing [ogmios' utxo by txin query](https://ogmios.dev/mini-protocols/local-state-query/#utxo-by-txin).

### Pre-review checklist

- [x] All code has been formatted using our config (`make format` for Purescript, `nixpkgs-fmt` for Nix)
- [x] All Purescript imports are explicit, including constructors
- [x] **All** existing examples have been run locally against a fully-synced testnet node
- [x] The integration and unit tests have been run (`npm run test`) locally
- [x] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`)

2022-07-07 19:07 UTC, klntsky commented on src/QueryM/Utxos.purs
> +-- | `getUtxo ref` queries for the utxo given by `ref`.
`Queries for UTxO given a transaction input`

2022-07-07 19:09 UTC, klntsky commented on src/Contract/Utxos.purs
> +-- | `getUtxo ref` queries for the utxo given by `ref`.
Same as below

2022-07-08 07:14 UTC, vvtran commented on src/QueryM/Ogmios.purs
> +  renameFields { transactionId, index } = { txId: transactionId, index }
We tend to have explicit type sigs inside `where` even if obvious.

2022-07-11 07:58 UTC, firefrorefiddle approved these changes

2022-07-11 10:06 UTC, klntsky requested changes

2022-07-11 10:06 UTC, klntsky commented on src/Contract/Utxos.purs
> +           "`utxosAt`: Querying for UTxOs by address is deprecated. See https://github.com/CardanoSolutions/ogmios/issues/199."
Please add this link instead: https://github.com/Plutonomicon/cardano-transaction-lib/issues/536

I think it's better to point users to our issue, to make it clear how we are going to handle that problem in the future.

2022-07-11 14:01 UTC, jy14898 requested changes

2022-07-12 11:07 UTC, klntsky commented
Looks good. Please resolve the conflict.

2022-07-12 17:42 UTC, klntsky approved these changes

2022-07-12 17:43 UTC, merged