Brian/better tx evaluation error
Plutonomicon/cardano-transaction-lib pull request #831
Opened 2022-08-01 20:46 UTC by Geometer1729

Closes # .

### Pre-review checklist

- [ ] All code has been formatted using our config (`make format` for Purescript, `nixpkgs-fmt` for Nix)
- [ ] All Purescript imports are explicit, including constructors
- [ ] The integration and unit tests have been run (`npm run test`) locally
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2022-08-01 20:55 UTC, Geometer1729 commented
`npm run test` is giving me
```
16/17 tests passed

[error] Running failed; exit code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cardano-transaction-lib@2.0.0-alpha integration-test: `spago run --main Test.Integration`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cardano-transaction-lib@2.0.0-alpha integration-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```
but `spago test` works. I'm not sure what to make of that.

2022-08-01 20:58 UTC, Geometer1729 commented
I'm checking off the changelog thing because I think it's fine that I haven't put anything in the changelog for this.

2022-08-02 02:44 UTC, jy14898 commented
Apologies for the duplicated work, I didn't yet create a PR for the work I've been doing on this issue, so I've made it available here: https://github.com/Plutonomicon/cardano-transaction-lib/pull/832

2022-08-02 16:45 UTC, klntsky requested changes

2022-08-02 16:45 UTC, klntsky commented on src/BalanceTx/BalanceTx.purs
> +          flip setRdmrsExecutionUnits (Map.fromFoldable xs) $
Do not call fromFoldable twice, introduce a variable.

2022-08-02 16:45 UTC, klntsky commented on src/BalanceTx/BalanceTx.purs
>  updateTxExecutionUnits unattachedTx rdmrPtrExUnitsList =
please change the argument name also.

2022-08-02 16:45 UTC, klntsky commented on src/QueryM/Ogmios.purs
> +      ( do
Parentheses are not required

2022-08-05 13:09 UTC, closed without merging