Add Contract.Extra
Plutonomicon/cardano-transaction-lib pull request #848
Opened 2022-08-03 13:17 UTC by samuelWilliams99

Closes # .

### Pre-review checklist

- [ ] All code has been formatted using our config (`make format` for Purescript, `nixpkgs-fmt` for Nix)
- [ ] All Purescript imports are explicit, including constructors
- [ ] The integration and unit tests have been run (`npm run test`) locally
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2022-08-04 12:24 UTC, ngua requested changes
Please run the formatter on this (`make format`)

There are ~30 warnings from compilation. You can look at the Hydra logs to see more adjustments that need to be made or just build the package with Nix locally: https://ci.staging.mlabs.city/build/200617/nixlog/1. Warnings are treated as errors on CI

2022-08-04 12:24 UTC, ngua commented on src/Contract/Extra.purs
> +oneshotPolicyStr :: String
I'd prefer not to embed this as a string, we have a new method for loading scripts, `Contract.TextEnvelope`

2022-08-04 12:24 UTC, ngua commented on test/OneShot.purs
> +-- Run with `spago test --main Test.Plutip`
Comment needs to be updated, but see my other comment about this module

2022-08-04 12:24 UTC, ngua commented on test/OneShot.purs
> +import Cardano.Types.Value (getNonAdaAsset)
We should use the Plutus version

2022-08-04 12:24 UTC, ngua commented on test/OneShot.purs
> +import Examples.MintsMultipleTokens (mintingPolicyRdmrInt1, mintingPolicyRdmrInt2, mintingPolicyRdmrInt3)
A lot of these imports are redundant

2022-08-04 12:24 UTC, ngua commented on test/OneShot.purs
> +module Test.OneShot
We can just move the tests and contracts to our existing `Test.Plutip` rather than having a dedicated module

2022-08-04 12:24 UTC, ngua commented on package.json
> +    "one-shot-test": "spago run --main Test.OneShot",
See my comment about `Test.OneShot`

2022-08-04 12:24 UTC, ngua commented on src/Contract/Extra.purs
> +  "5901c5010000323232323232323232222332232325333009332300b22533300e00114a02a6646601a0022944c00cc0400044c008c03c0048c8cdd7803000980718048009bac001149854cc03924114446f65736e277420636f6e73756d6520757478
Where's does this come from? Can you provide a link to the onchain code? I'd actually prefer not to have a `Contract.Extra` and instead have a `ctl-extra` repo that contains both the onchain and offchain code, along with serialization scripts

2022-08-04 12:24 UTC, ngua commented on src/Contract/Extra.purs
> +  { oscAmounts :: Map.Map TokenName BigInt.BigInt
This type of field naming isn't really idiomatic in Purescript

2022-08-04 12:24 UTC, ngua commented
Also please complete the PR template

2022-08-11 04:48 UTC, ngua commented
I'm going to close this for now as it needs a fair amount of work and I'd prefer not to have `Contract.Extra` live in the CTL repo. As I mentioned in another comment, I think it would be best to have a separate repo that also contains the onchain code and serialization scripts

That said, if anyone wants to continue with this approach please feel free to reopen!

2022-08-11 04:48 UTC, closed without merging

2022-08-11 08:59 UTC, samuelWilliams99 commented
Hi apologies, this was made in a mob session, and I haven't had time to come back to it. Perhaps we can get some kind of `ctl-util-contracts` repo that contains a bunch of small onchain utils with their related offchain.

2022-08-11 09:24 UTC, klntsky commented
@samuelWilliams99 no worries, thank you anyway! I think we may want to adapt this code for tests.