Add Flint wallet support
Plutonomicon/cardano-transaction-lib pull request #878
Opened 2022-08-10 22:36 UTC by amirmrad

Closes #556 .

### Pre-review checklist

- [ ] All code has been formatted using our config (`make format`)
- [ ] The integration and unit tests have been run (`npm run test`) locally
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2022-08-11 09:23 UTC, klntsky commented on src/Wallet.purs
>    _ -> Nothing
Come to think of it, we should not use wildcard pattern here to make it harder to forget to add a new wallet when we do it.

2022-08-12 09:57 UTC, klntsky commented
I am getting 

```
Uncaught Error: `submit` call failed. Error from Ogmios: [{"valueNotConserved":{"consumed":{"assets":{},"coins":0},"produced":{"assets":{"fda1b6b487bee2e7f64ecf24d24b1224342484c0195ee1b7b943db50.546865546f6b656e":100},"coins":1002989232}}},{"badInputs":[{"index":0,"txId":"962c7e6204e5b4e0e53b87f5ca10d0819af04d4cf97407d18982956a8da0a800"},{"index":1,"txId":"bc8dca6432b09b8c75b78462ae339707b6fa850c8d005f300df78c792484a427"},{"index":0,"txId":"c227876b250f21327a8f69ab5e8737136e5cbf188e89cda30404781195dcb947"}]}]

```

on http://localhost:8000/?SignMultiple:flint

2022-08-12 10:02 UTC, klntsky commented
Probably a concurrent spending problem. I think I was running another example in parallel.

2022-08-12 10:04 UTC, klntsky approved these changes

2022-08-12 10:14 UTC, ngua requested changes
Please update the wallet list in the readme, otherwise LGTM

2022-08-13 04:10 UTC, ngua approved these changes

2022-08-13 04:17 UTC, merged