Rewrite the balancing algorithm so that tx is always pre-balanced before ex units calculation
Plutonomicon/cardano-transaction-lib pull request #910
Opened 2022-08-16 22:45 UTC by errfrom

Closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/892

### Pre-review checklist

- [ ] All code has been formatted using our config (`make format`)
- [x] The integration and unit tests have been run (`npm run test`) locally
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2022-08-19 05:10 UTC, ngua requested changes
Excellent work! AFAICT the new, simplified balancer is working correctly and I am very much in favor of the changes you introduce here

My request for changes is not related to your work. I just think this is good opportunity to further cut down on some earlier technical debt in CTL

2022-08-20 05:04 UTC, ngua reviewed
Great work! Just a couple of final things. I can take care of these now to merge this in more quickly

2022-08-20 05:04 UTC, ngua commented on src/BalanceTx/Error.purs
> +module BalanceTx.Error
Could use a module doc comment

2022-08-20 05:16 UTC, ngua approved these changes

2022-08-20 05:26 UTC, errfrom commented
@ngua Thanks for your review! I would like to make some more changes real quick, and then we can merge it

2022-08-20 06:42 UTC, ngua approved these changes

2022-08-20 06:52 UTC, merged