Add examples for `PlutusV2` reference scripts and reference inputs
Plutonomicon/cardano-transaction-lib pull request #946
Opened 2022-08-24 15:55 UTC by errfrom

Partially closes https://github.com/Plutonomicon/cardano-transaction-lib/issues/922

### Pre-review checklist

- [ ] All code has been formatted using our config (`make format`)
- [ ] Any new API feature includes a full example or integration test run with Plutip on CI
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2022-08-25 07:27 UTC, ngua commented on src/Types/TxConstraints.purs
> +mustIncludeReferenceInput
I thought we were going to wait to add the new constraints until after the v2.0.0 release, but I'm reconsidering that now
- you've already implemented these
- the changes are largely backwards-compatible and unobtrusive
- we have a growing number of projects who want to use the new features (at least three for sure)

So I think we should keep the new constraints. We just need to deal with `Datum` arguments to other ones (not related to this PR)

2022-09-01 09:07 UTC, klntsky requested changes
This naming sounds better. Also, most likely user will search for functions using a prefix like `mustPayTo...` with docs-search, that can only look up prefixes.

2022-09-01 09:07 UTC, klntsky commented on src/Types/TxConstraints.purs
> +mustPayWithDatumToPubKeyAddress
`mustPayToPubKeyAddressWithDatum`

2022-09-01 09:07 UTC, klntsky commented on src/Types/TxConstraints.purs
> +mustPayWithScriptRefToPubKeyAddress
`mustPayToPubKeyAddressWithScriptRef`

2022-09-01 09:07 UTC, klntsky commented on src/Types/TxConstraints.purs
> +mustPayWithDatumAndScriptRefToPubKeyAddress
`mustPayToPubKeyAddressWithDatumAndScriptRef`

2022-09-01 09:07 UTC, klntsky commented on src/Types/TxConstraints.purs
> +mustPayWithDatumToPubKey
`mustPayToPubKeyWithDatum`

2022-09-01 09:07 UTC, klntsky commented on src/Types/TxConstraints.purs
> +mustPayWithScriptRefToPubKey
`mustPayToPubKeyWithScriptRef`

2022-09-01 09:07 UTC, klntsky commented on src/Types/TxConstraints.purs
> +mustPayWithDatumAndScriptRefToPubKey
`mustPayToPubKeyWithDatumAndScriptRef`

2022-09-01 09:07 UTC, klntsky commented on src/Types/TxConstraints.purs
> +mustPayWithScriptRefToScript
`mustPayToScriptWithScriptRef`

2022-09-05 14:53 UTC, klntsky approved these changes

2022-09-06 04:45 UTC, ngua commented
I'm going to build the checks locally since Hydra is down. If it works I'll merge this

2022-09-06 05:01 UTC, ngua approved these changes
The checks work locally, merging

2022-09-06 05:01 UTC, merged