maybes removed from ProtocolParameters
Plutonomicon/cardano-transaction-lib pull request #990
Opened 2022-09-05 11:09 UTC by pb99u069

Closes # .

### Pre-review checklist

- [ ] All code has been formatted using our config (`make format`)
- [ ] Any new API features or modification of existing behavior is covered as defined in our [test plan](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/test-plan.md)
- [ ] The changelog has been updated under the `## Unreleased` header, using the appropriate sub-headings (`### Added`, `### Removed`, `### Fixed`), and the links to the appropriate issues/PRs have been included

2022-09-05 14:50 UTC, klntsky requested changes

2022-09-05 14:50 UTC, klntsky commented on CHANGELOG.md
> +- The `ProtocolParameters` introduced in Alonzo (`prices`, `maxTxExUnits`, `maxBlockExUnits`, `maxValueSize`, `collateralPercent` and `maxCollateralInputs`) are no longer of type `Maybe` ([#971](http
Please add `because we don't support pre-Alonzo eras`

2022-09-05 15:25 UTC, klntsky requested changes

2022-09-05 15:25 UTC, klntsky commented on src/QueryM/Ogmios.purs
> +      pure $ { memPrice, stepPrice } -- ExUnits
```suggestion
      pure { memPrice, stepPrice } -- ExUnits
```

Dollar is not needed in PS here

2022-09-06 09:15 UTC, klntsky approved these changes

2022-09-09 09:55 UTC, klntsky submitted a review, later dismissed
@pb99u069 please make it compile (I didn't notice it's not building because the CI was broken)

2022-09-13 14:37 UTC, errfrom approved these changes

2022-09-13 18:06 UTC, merged